name: Rust

on:
  push:
    branches: [ "github_actions" ]
  pull_request:
    branches: [ "github_actions" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: SetUpDB
      run: sudo apt update && sudo apt upgrade
    - run: chmod +x docker_setup.script && ./docker_setup.script.sh
    - run: sudo apt-get install postgresql
    - run: cargo install sqlx-cli
    - run: ./db_setup_script.sh
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
